version: "3"

tasks:
  test:
    desc: Run pytest tests
    cmds:
      - uv run pytest .

  clean-notebooks:
    desc: Strip output from Jupyter notebooks
    cmds:
      - find . -name "*.ipynb" -exec nbstripout {} \;
