from loguru import logger
import pandas as pd
from pydantic import BaseModel
from typing import List

from ngv_reports_ibkr.custom_flex_report import CustomFlexReport

class ReportOutputAdapterCSV(BaseModel):
    """
    Adapter responsible for writing Report Sections to disk.
    """

    class Config:
        arbitrary_types_allowed = True

    data_folder: str = "data"
    report: CustomFlexReport

    def process_accounts(self):
        for account_id in self.report.account_ids():
            logger.info(f"CSV output adapter for {account_id}")
            self.put_all(aid=account_id)

    def put_all(self, aid: str):
        self.put_trades(aid)
        self.put_close_trades(aid)
        self.put_open_positions(aid)

    def _gen_file_name(self, aid: str, name: str) -> str:
        return f"{self.data_folder}/{aid}_{name}.csv"

    def _put_df(self, aid: str, df: pd.DataFrame, section: str) -> None:
        fn = self._gen_file_name(aid, section)
        df.to_csv(fn)

    def put_trades(self, aid):
        df = self.report.trades_by_account_id(aid)
        if df is None:
            logger.warning(
                f"AccountId={aid}. Unable to get trades data from report. "
                "Does the Flex Report have Trades turned on?"
            )
            return
        self._put_df(aid, df, "trades")

    def put_close_trades(self, aid):
        df = self.report.closed_trades_by_account_id(aid)
        if df is None:
            logger.warning(
                f"AccountId={aid}. Unable to get trades data from report. "
                "Does the Flex Report have Trades turned on?"
            )
            return
        self._put_df(aid, df, "close_trades")

    def put_open_positions(self, aid):
        df = self.report.open_positions_by_account_id(aid)
        if df is None:
            logger.warning(
                f"AccountId={aid}. Unable to get positions data from report. "
                "Does the Flex Report have Positions turned on?"
            )
            return
        self._put_df(aid, df, "open_positions")


class ReportOutputAdapterPandas(BaseModel):
    """
    Adapter responsible for returning Report Sections as dictionary of Panda DataFrames.
    """
    class Config:
        arbitrary_types_allowed = True
    
    report: CustomFlexReport

    def process_accounts(self) -> List[dict]:
        """
        For each account, generate a dict of DataFrames for all sections.

        Returns:
            List[dict]: list of dicts of dfs (generated by put_all)
        """
        results = []
        for account_id in self.report.account_ids():
            logger.info(f"Pandas output adapter for {account_id}")
            dict_of_dfs = self.put_all(aid=account_id)
            results.append(dict_of_dfs)
        return results

    def put_trades(self, aid: str) -> pd.DataFrame:
        """
        Generate a DataFrame of trades for a given account id

        Args:
            aid (str): account id

        Returns:
            pd.DataFrame: df of trades
        """
        df = self.report.trades_by_account_id(aid)
        if df is None:
            logger.warning(
                f"AccountId={aid}. Unable to get trades data from report. "
                "Does the Flex Report have Trades turned on?"
            )
            return None
        return df
    
    def put_close_trades(self, aid: str) -> pd.DataFrame:
        """
        Generate a DataFrame of closed trades for a given account id

        Args:
            aid (str): account id

        Returns:
            pd.DataFrame: df of close trades
        """
        df = self.report.closed_trades_by_account_id(aid)
        if df is None:
            logger.warning(
                f"AccountId={aid}. Unable to get trades data from report. "
                "Does the Flex Report have Trades turned on?"
            )
            return
        return df

    def put_open_positions(self, aid: str) -> pd.DataFrame:
        """
        Generate a DataFrame of open positions for a given account id

        Args:
            aid (str): account id

        Returns:
            pd.DataFrame: df of trades
        """
        df = self.report.open_positions_by_account_id(aid)
        if df is None:
            logger.warning(
                f"AccountId={aid}. Unable to get positions data from report. "
                "Does the Flex Report have Positions turned on?"
            )
            return None
        return df

    def put_all(self, aid: str) -> dict:
        """
        Generate a dict of DataFrames for all sections

        Args:
            aid (str): account id

        Returns:
            dict: dict of dfs
        """
        return {
            "trades": self.put_trades(aid),
            "closed_trades": self.put_close_trades(aid),
            "open_positions": self.put_open_positions(aid),
        }
